server:
  port: 8080

spring:
  application:
    name: saga-financeira

  kafka:
    bootstrap-servers: host.docker.internal:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

    consumer:
      group-id: saga-financeira-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.example.sbkafka.event.EventoTransferencia

    listener:
      ack-mode: record

  datasource:
    url: jdbc:postgresql://localhost:5432/saga_db
    username: saga_user
    password: saga_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    # não configurar default_schema para usar o schema público existente

  sql:
    init:
      mode: never

app:
  kafka:
    topic: pedidos-topic
